-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 13:46:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cidadeDosVegetais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cidadeDosVegetais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cidadeDosVegetais` DEFAULT CHARACTER SET utf8 ;
USE `cidadeDosVegetais` ;

-- -----------------------------------------------------
-- Table `cidadeDosVegetais`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidadeDosVegetais`.`table1` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `classificacao` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidadeDosVegetais`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidadeDosVegetais`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidadeDosVegetais`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidadeDosVegetais`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `estoque` BIGINT NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  INDEX `fk_tb_produtos_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `cidadeDosVegetais`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
